GCBenchBenchmark using SafeZone
Run from repo's root on dev branch `ENABLE_EXPERIMENTAL_COMPILER=true sbt "sandbox3_next/compile"`

Failed to compile `alloc(new Node(makeTree(iDepth - 1), makeTree(iDepth - 1), 0, 0))`

[error] -- [E007] Type Mismatch Error: /Users/a.mordovskiy/scala-native-playground/scala-native/sandbox/src/main/scala-next/Test.scala:13:15
[error] 13 |    SafeZone { sz ?=>
[error]    |               ^
[error]    |Found:    (sz: scala.scalanative.memory.SafeZone^'s1) ?->'s2 Boolean
[error]    |Required: (scala.scalanative.memory.SafeZone^) ?=> Boolean
[error]    |
[error]    |Note that capability `any` is not included in capture set {}.
[error]    |
[error]    |where:    ?=> refers to a root capability created in method run when checking argument to parameter f of method apply
[error]    |          ^   refers to the root capability caps.any
[error]    |          any is a root capability created in anonymous function of type (using sz: scala.scalanative.memory.SafeZone^'s1): Boolean of parameter parameter sz² of method $anonfun
[error]    |
[error] 14 |      class Node(var left: Node^{sz}, var right: Node^{sz}, var i: Int, var j: Int)
[error] 15 |...
[error] 85 |      longLivedTree != null && array(1000) == 1.0 / 1000
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (sandbox3_next / Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 6 Feb 2026, 13:37:12